# List vs Array

In [79]:
import numpy as np

L=[1,2,3]

for e in L:
        print(e)


1
2
3


In [88]:
A =np.array([[1,2,3]])

for e in A:
    print(A)
    
    

[[1 2 3]]


In [7]:
L.append(4)
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
L= L+[5]
L

[1, 2, 3, 4, 5]

In [11]:
A = A+[4,5]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
L2=[]
for e in L:
    L2.append(e+e)
L2    
          

[2, 4, 6, 8, 10]

In [13]:
A+A

array([2, 4, 6])

In [14]:
2*A

array([2, 4, 6])

In [15]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [16]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [17]:
L2=[]
for e in L:
    L2.append(e*e)
L2    

[1, 4, 9, 16, 25]

In [18]:
A**2

array([1, 4, 9])

In [19]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [20]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [21]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Dot product :- Dot Function

In [24]:
a= np.array([1,2])
b= np.array([2,1])

dot=0
for e,f in zip(a,b):
    dot+=e*f
dot    

4

In [25]:
a*b

array([2, 2])

In [26]:
np.sum(a*b)

4

In [27]:
(a*b).sum()

4

In [28]:
np.dot(a, b)


4

In [30]:
a.dot(b)

4

In [31]:
b.dot(a)

4

In [33]:
#To calculate angle between a and b first calculate length vector of a and b.
#amag(amagnitude)
amag=np.sqrt((a*a).sum())
amag

2.23606797749979

In [34]:
amag= np.linalg.norm(a)
amag

2.23606797749979

In [35]:
#Calculate angle
cosangle= a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.7999999999999998

In [37]:
#Actual angle is:-
angle=np.arccos(cosangle)
angle

0.6435011087932847

In [74]:
M=np.array([[1,2],[3,4]])
L=[[1,2], [3,4]]
 

M2=np.matrix([[1,2], [2,3]])
M2

matrix([[1, 2],
        [2, 3]])

In [77]:
A=np.array(M2)
A

array([[1, 2],
       [2, 3]])

In [78]:
A.T

array([[1, 2],
       [2, 3]])